# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import wiki.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('revision', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=models.SET(wiki.models.get_sentinel_user), related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
